CREATE TABLE IF NOT EXISTS public.products (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(150) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Category" character varying(100) NOT NULL,
    "Images" text[] NOT NULL DEFAULT ARRAY[]::text[],
    "Price" numeric(18,2) NOT NULL,
    "StockQuantity" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);

ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS "Category" character varying(100) NOT NULL DEFAULT '';

ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS "Images" text[] NOT NULL DEFAULT ARRAY[]::text[];
